#if !canImport(ObjectiveC)
import XCTest

extension ExecuteStatementTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ExecuteStatementTests = [
        ("testDecodeBool", testDecodeBool),
        ("testDecodeDouble", testDecodeDouble),
        ("testDecodeIsNull", testDecodeIsNull),
        ("testDecodeLong", testDecodeLong),
        ("testDecodeString", testDecodeString),
        ("testEncodeBool", testEncodeBool),
        ("testEncodeDouble", testEncodeDouble),
        ("testEncodeIsNull", testEncodeIsNull),
        ("testEncodeLong", testEncodeLong),
        ("testEncodeString", testEncodeString),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ExecuteStatementTests.__allTests__ExecuteStatementTests),
    ]
}
#endif
